[package]
name = "linkshort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
mysql = "24"
serde = "1.0.190"
dotenvy = "0.15.7"
env_logger = "0.9.3"
url = "2"